os: linux
dist: xenial
language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc
  - sudo apt-get install -y g++
  - sudo apt-get install -y libprotobuf-dev
  - sudo apt-get install -y protobuf-compiler
  - sudo apt-get install -y cmake
  - sudo apt-get install -y python
#  - sudo apt-get install -y swig
  - sudo apt-get install -y bc
  - sudo apt-get install -y kmod
  - sudo apt-get install -y linux-headers-$(uname -r)

script:
  - ./configure
  - make
  - make test
  - sudo make install
  - sudo make depmod
  - sudo make intest
  - ./configure --debug
  - make
  - make test
  - sudo make install
  - sudo make depmod
  - sudo make intest
